// 🤖 Generated by Xcode Coding Intelligence powered by Claude Sonnet 4
// 🧑 Reviewed and modified by human

import Foundation
import LanguageModelClientInterface
import Utils

public struct MockLanguageModelClient {
    private let tokens: [String]
    private let shouldThrowError: Bool
    private let delayBetweenTokens: Double
    
    public init(
        tokens: [String] = [],
        shouldThrowError: Bool = false,
        delayBetweenTokens: Double = 0.1
    ) {
        self.tokens = tokens
        self.shouldThrowError = shouldThrowError
        self.delayBetweenTokens = delayBetweenTokens
    }
}

extension MockLanguageModelClient: LanguageModelClientInterface {
    public func streamResponse(to prompt: String) -> sending AsyncThrowingStream<String, any Error> {
        AsyncThrowingStream { continuation in
            let tokens = self.tokens
            let shouldThrowError = self.shouldThrowError
            let delayBetweenTokens = self.delayBetweenTokens
            
            Task {
                do {
                    if shouldThrowError {
                        throw MockLanguageModelError.simulatedError
                    }
                    
                    for response in tokens.toLanguageModelResponses() {
                        try await Task.sleep(for: .seconds(delayBetweenTokens))
                        continuation.yield(response)
                    }
                    
                    continuation.finish()
                } catch {
                    continuation.finish(throwing: error)
                }
            }
        }
    }
}

public enum MockLanguageModelError: LocalizedError {
    case simulatedError
    
    public var errorDescription: String? {
        switch self {
        case .simulatedError: "시뮬레이션된 에러입니다."
        }
    }
}

public extension [String] {
    func toLanguageModelResponses() -> [String] {
        self.mapReduce(into: "") { response, token in
            response += token
            return response
        }
    }
}
