// 🤖 Generated by Xcode Coding Intelligence powered by Claude Sonnet 4
// 🧑 Reviewed and modified by human

@testable import ChatFeature
import LanguageModelClientTesting
import Testing

@Suite("ChatFeatureUseCase")
struct ChatFeatureUseCaseTests {
    @Test("응답 스트림이 에러를 정상적으로 전파하는지 테스트")
    func testStreamResponseWithError() async throws {
        // Given
        let mockClient = MockLanguageModelClient(shouldThrowError: true)
        let useCase = ChatFeatureUseCase(repository: mockClient)
        let prompt = "프롬프트"
        
        // When & Then
        await #expect(throws: MockLanguageModelError.self) {
            for try await _ in useCase.streamResponse(to: prompt) {}
        }
    }
    
    @Test("빈 응답 스트림 테스트")
    func testStreamResponseWithEmptyResponse() async throws {
        // Given
        let mockClient = MockLanguageModelClient(tokens: [])
        let useCase = ChatFeatureUseCase(repository: mockClient)
        let prompt = "프롬프트"
        
        // When
        var receivedResponses = [String]()
        for try await response in useCase.streamResponse(to: prompt) {
            receivedResponses.append(response)
        }
        
        // Then
        #expect(receivedResponses.isEmpty, "빈 응답 스트림의 경우 받은 응답도 비어있어야 합니다.")
    }
    
    @Test("단일 토큰 응답 스트림 테스트")
    func testStreamResponseWithSingleToken() async throws {
        // Given
        let singleToken = "단일토큰"
        let mockClient = MockLanguageModelClient(tokens: [singleToken])
        let useCase = ChatFeatureUseCase(repository: mockClient)
        let prompt = "프롬프트"
        
        // When
        var receivedResponses = [String]()
        for try await response in useCase.streamResponse(to: prompt) {
            receivedResponses.append(response)
        }
        
        // Then
        #expect(receivedResponses == [singleToken], "받은 응답이 기대하는 응답과 일치해야 합니다.")
    }
    
    @Test("많은 토큰 수의 응답 스트림 테스트")
    func testStreamResponseWithLargeNumberOfTokens() async throws {
        // Given
        let largeNumberOfTokens = Array(1...100).map { "토큰\($0)" }
        let mockClient = MockLanguageModelClient(
            tokens: largeNumberOfTokens,
            delayBetweenTokens: 0.01
        )
        let useCase = ChatFeatureUseCase(repository: mockClient)
        let prompt = "프롬프트"
        
        // When
        var receivedResponses = [String]()
        for try await response in useCase.streamResponse(to: prompt) {
            receivedResponses.append(response)
        }
        
        // Then
        let expectedResponses = largeNumberOfTokens.toLanguageModelResponses()
        #expect(receivedResponses == expectedResponses, "받은 응답들이 기대하는 응답들과 일치해야 합니다.")
    }
}
