// 🤖 Generated by Xcode Coding Intelligence powered by Claude Sonnet 4
// 🧑 Reviewed and modified by human

import Utils
import Testing

@Suite("Array mapReduce")
struct ArrayMapReduceTests {
    @Test("정수 누적 합계 테스트")
    func testAccumulatingSum() {
        // Given
        let numbers = [1, 2, 3, 4, 5]
        
        // When
        let results = numbers.mapReduce(into: Int.zero) { accumulated, number in
            accumulated += number
            return accumulated
        }
        
        // Then
        #expect(results == [1, 3, 6, 10, 15], "정수의 누적 합계를 반환해야 함")
    }
    
    @Test("문자열 누적 테스트")
    func testAccumulatingString() {
        // Given
        let words = ["Hello", "Swift", "Testing"]
        
        // When
        let results = words.mapReduce(into: "") { accumulated, word in
            accumulated += word
            return accumulated
        }
        
        // Then
        #expect(results == ["Hello", "HelloSwift", "HelloSwiftTesting"], "누적된 문자열을 반환해야 함")
    }
    
    @Test("빈 배열 테스트")
    func testEmptyArray() {
        // Given
        let emptyArray = [Int]()
        
        // When
        let results = emptyArray.mapReduce(into: Int.zero) { _, _ in Int.zero }
        
        // Then
        #expect(results.isEmpty, "빈 배열을 반환해야 함")
    }
    
    @Test("다소 복잡한 객체 테스트")
    func testComplexObject() {
        struct Counter: Equatable {
            var count = 0
            var sum = 0
        }
        
        // Given
        let numbers = [10, 20, 30]
        
        // When
        let results = numbers.mapReduce(into: Counter()) { counter, number in
            counter.sum += number
            counter.count += 1
            return counter
        }
        
        // Then
        let expectedResults: [Counter] = [
            Counter(count: 1, sum: 10),
            Counter(count: 2, sum: 30),
            Counter(count: 3, sum: 60),
        ]
        #expect(results == expectedResults, "기대하는 결과와 일치해야 함")
    }
    
    @Test("에러 전파 테스트")
    func testErrorPropagation() {
        enum MockError: Error {
            case simulatedError
        }
        
        // Given
        let numbers = [0, 1, 0]
        
        // When & Then
        #expect(throws: MockError.simulatedError) {
            try numbers.mapReduce(into: Int.zero) { accumulated, number in
                if number > .zero {
                    throw MockError.simulatedError
                }
                accumulated += number
                return accumulated
            }
        }
    }
}
